"""
auto_cookie_refresh.py — YouTube Cookies Auto-Refresh (v2 — SAPISID Fix)
=========================================================================
Fix: Ab google.com cookies bhi capture hoti hain (SAPISID, SID, HSID, etc.)
Cron se weekly chalao — bar bar manual cookies ki zaroorat nahi.

Setup:
  pip install playwright --break-system-packages
  playwright install chromium --with-deps

Usage:
  python3 auto_cookie_refresh.py --headless        # EC2 pe
  python3 auto_cookie_refresh.py --headless --force # force refresh

Cron (weekly Sunday 3am):
  0 3 * * 0 cd ~/be/bot_v12 && python3 auto_cookie_refresh.py --headless >> logs/cookie_refresh.log 2>&1
"""

import os, sys, json, time, logging, argparse, sqlite3, shutil
from datetime import datetime

# ── Config ────────────────────────────────────────────────────────────────────
_BOT_DIR    = os.path.dirname(os.path.abspath(__file__))
COOKIE_FILE = os.path.join(_BOT_DIR, "yt_cookies.txt")
CREDS_FILE  = os.path.join(_BOT_DIR, "yt_creds.json")
DB_PATH     = os.path.join(_BOT_DIR, "data.db")
LOG_DIR     = os.path.join(_BOT_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(os.path.join(LOG_DIR, "cookie_refresh.log"))
    ]
)
log = logging.getLogger("cookie_refresh")

# ── Credentials ───────────────────────────────────────────────────────────────
def load_credentials():
    if not os.path.exists(CREDS_FILE):
        log.error(f"Credentials file nahi mili: {CREDS_FILE}")
        log.error('Banao: echo \'{"email":"x@gmail.com","password":"pass"}\' > yt_creds.json')
        sys.exit(1)
    with open(CREDS_FILE) as f:
        creds = json.load(f)
    if not creds.get("email") or not creds.get("password"):
        log.error("yt_creds.json mein email aur password dono chahiye")
        sys.exit(1)
    return creds["email"], creds["password"]

# ── Netscape format ───────────────────────────────────────────────────────────
def to_netscape(cookies):
    """Playwright cookies → yt-dlp compatible Netscape format"""
    lines = ["# Netscape HTTP Cookie File", "# This file is generated by yt-dlp.  Do not edit.", ""]
    for c in cookies:
        domain  = c.get("domain", "")
        flag    = "TRUE" if domain.startswith(".") else "FALSE"
        path    = c.get("path", "/")
        secure  = "TRUE" if c.get("secure", False) else "FALSE"
        expires = str(int(c.get("expires", 0))) if c.get("expires", 0) > 0 else "0"
        name    = c.get("name", "")
        value   = c.get("value", "")
        if not name: continue
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines)

# ── Main refresh ──────────────────────────────────────────────────────────────
def refresh_cookies(headless=True):
    try:
        from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
    except ImportError:
        log.error("pip install playwright && playwright install chromium --with-deps")
        return False

    email, password = load_credentials()
    log.info(f"Cookie refresh shuru — headless={headless}, account={email}")

    with sync_playwright() as p:
        browser = p.chromium.launch(
            executable_path="/usr/bin/chromium-browser",
            headless=headless,
            args=[
                "--no-sandbox", "--disable-setuid-sandbox",
                "--disable-dev-shm-usage", "--disable-gpu",
                "--disable-blink-features=AutomationControlled",
            ]
        )
        context = browser.new_context(
            viewport={"width": 1280, "height": 720},
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            locale="en-US",
        )
        page = context.new_page()

        try:
            # ── Step 1: Google login page ──────────────────────────────────
            log.info("Google login page khol raha hoon...")
            page.goto("https://accounts.google.com/signin", timeout=30000)
            time.sleep(2)

            # ── Step 2: Email ──────────────────────────────────────────────
            log.info("Email enter kar raha hoon...")
            page.wait_for_selector('input[type="email"]', timeout=15000)
            page.fill('input[type="email"]', email)
            page.keyboard.press("Enter")
            time.sleep(3)

            # ── Step 3: Password ───────────────────────────────────────────
            log.info("Password enter kar raha hoon...")
            page.wait_for_selector('input[type="password"]', timeout=15000)
            page.fill('input[type="password"]', password)
            page.keyboard.press("Enter")
            time.sleep(4)

            # ── Step 4: Login check ────────────────────────────────────────
            cur = page.url
            log.info(f"Current URL after login: {cur}")

            if "challenge" in cur or "signin/challenge" in cur or "2-step" in cur:
                log.error("❌ 2FA required — account mein 2FA band karo ya App Password use karo")
                browser.close()
                return False

            # ── Step 5: Google.com pe jao — SAPISID milegi ────────────────
            log.info("google.com pe ja raha hoon (SAPISID ke liye)...")
            page.goto("https://www.google.com", timeout=20000)
            time.sleep(2)

            # ── Step 6: YouTube pe jao ─────────────────────────────────────
            log.info("YouTube pe ja raha hoon...")
            page.goto("https://www.youtube.com", timeout=20000)
            time.sleep(3)

            # ── Step 7: Confirm login ──────────────────────────────────────
            # Check: agar avatar/profile visible hai to logged in hain
            try:
                page.wait_for_selector('button#avatar-btn, yt-img-shadow#avatar', timeout=8000)
                log.info("✅ YouTube pe logged in confirm ho gaya")
            except PWTimeout:
                log.warning("Avatar nahi mila — par continue kar raha hoon")

            # ── Step 8: ALL cookies collect karo (koi filter nahi) ─────────
            log.info("Saari cookies collect kar raha hoon...")
            all_cookies = context.cookies([
                "https://www.google.com",
                "https://accounts.google.com",
                "https://www.youtube.com",
            ])

            log.info(f"Total cookies mili: {len(all_cookies)}")

            # Debug: konsi auth cookies hain
            important = ["SAPISID", "APISID", "SID", "HSID", "SSID",
                        "__Secure-3PSID", "__Secure-3PAPISID", "LOGIN_INFO"]
            found = [c["name"] for c in all_cookies if c["name"] in important]
            missing = [n for n in important if n not in found]
            log.info(f"✅ Auth cookies mili: {found}")
            if missing:
                log.warning(f"⚠️ Missing: {missing}")

            # SAPISID check — ye zaroor honi chahiye
            if "SAPISID" not in found:
                log.error("❌ SAPISID nahi mili — login properly nahi hua")
                log.error("Possible reasons: 2FA, wrong password, account suspended")
                browser.close()
                return False

            if len(all_cookies) < 10:
                log.error(f"❌ Bahut kam cookies: {len(all_cookies)} — login fail")
                browser.close()
                return False

            # ── Step 9: Save ───────────────────────────────────────────────
            if os.path.exists(COOKIE_FILE):
                shutil.copy2(COOKIE_FILE, COOKIE_FILE + ".bak")

            content = to_netscape(all_cookies)
            with open(COOKIE_FILE, "w") as f:
                f.write(content)

            size = os.path.getsize(COOKIE_FILE)
            log.info(f"✅ Cookies saved: {COOKIE_FILE} ({size} bytes, {len(all_cookies)} cookies)")

            # ── Step 10: DB update ─────────────────────────────────────────
            try:
                conn = sqlite3.connect(DB_PATH, timeout=10)
                conn.execute("INSERT OR REPLACE INTO config(key,value) VALUES('youtube_cookies_enabled','1')")
                conn.execute(f"INSERT OR REPLACE INTO config(key,value) VALUES('yt_cookies_last_refresh','{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}')")
                conn.commit()
                conn.close()
                log.info("✅ DB updated — youtube_cookies_enabled=1")
            except Exception as e:
                log.warning(f"DB update fail: {e}")

            browser.close()
            log.info("🎉 Cookie refresh complete! Bot ab YouTube download kar sakta hai.")
            return True

        except Exception as e:
            log.error(f"❌ Error: {e}")
            try: browser.close()
            except: pass
            return False

# ── Health check ──────────────────────────────────────────────────────────────
def check_cookie_health():
    if not os.path.exists(COOKIE_FILE):
        return False, 0, "Cookie file nahi hai"
    size = os.path.getsize(COOKIE_FILE)
    if size < 200:
        return False, 0, f"File bahut choti hai ({size} bytes)"

    # SAPISID check
    with open(COOKIE_FILE) as f:
        content = f.read()
    if "SAPISID" not in content:
        return False, 0, "SAPISID missing — invalid cookies"

    import time as _t
    age_days = (_t.time() - os.path.getmtime(COOKIE_FILE)) / 86400
    if age_days > 10:
        return False, int(age_days), f"Cookies {int(age_days)} din purani — refresh karo"
    return True, int(age_days), f"Cookies theek hain ({int(age_days)} din purani, SAPISID present)"

# ── CLI ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--check",    action="store_true")
    parser.add_argument("--force",    action="store_true")
    args = parser.parse_args()

    if args.check:
        valid, age, msg = check_cookie_health()
        print(f"{'✅ VALID' if valid else '❌ INVALID'} — {msg}")
        sys.exit(0 if valid else 1)

    if not args.force:
        valid, age, msg = check_cookie_health()
        if valid:
            log.info(f"{msg} — refresh ki zaroorat nahi. --force se override karo.")
            sys.exit(0)

    success = refresh_cookies(headless=args.headless)
    sys.exit(0 if success else 1)
