"""
auto_cookie_refresh.py — YouTube Cookies Auto-Refresh
=====================================================
EC2 pe automatically YouTube login karke cookies save karta hai.
Cron se weekly chalao — bar bar manual cookies ki zaroorat nahi.

Setup:
  pip install playwright --break-system-packages
  playwright install chromium --with-deps

Usage:
  python3 auto_cookie_refresh.py                    # manual run
  python3 auto_cookie_refresh.py --headless         # headless mode (EC2)

Cron (weekly Sunday 3am):
  0 3 * * 0 cd /home/ubuntu/bot && python3 auto_cookie_refresh.py --headless >> logs/cookie_refresh.log 2>&1
"""

import os, sys, json, time, logging, argparse, sqlite3, shutil
from datetime import datetime

# ── Config ────────────────────────────────────────────────────────────────────
_BOT_DIR     = os.path.dirname(os.path.abspath(__file__))
COOKIE_FILE  = os.path.join(_BOT_DIR, "yt_cookies.txt")
CREDS_FILE   = os.path.join(_BOT_DIR, "yt_creds.json")       # YouTube login credentials
DB_PATH      = os.path.join(_BOT_DIR, "data.db")
LOG_DIR      = os.path.join(_BOT_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(os.path.join(LOG_DIR, "cookie_refresh.log"))
    ]
)
log = logging.getLogger("cookie_refresh")

# ── Credentials helper ────────────────────────────────────────────────────────
def load_credentials():
    """
    yt_creds.json se YouTube login credentials load karo.
    Format: {"email": "...", "password": "..."}
    """
    if not os.path.exists(CREDS_FILE):
        log.error(f"Credentials file nahi mili: {CREDS_FILE}")
        log.error("Banao: echo '{\"email\":\"your@gmail.com\",\"password\":\"yourpass\"}' > yt_creds.json")
        sys.exit(1)
    try:
        with open(CREDS_FILE) as f:
            creds = json.load(f)
        if not creds.get("email") or not creds.get("password"):
            log.error("yt_creds.json mein email aur password dono chahiye")
            sys.exit(1)
        return creds["email"], creds["password"]
    except Exception as e:
        log.error(f"Credentials load fail: {e}")
        sys.exit(1)

# ── Netscape cookie format converter ─────────────────────────────────────────
def playwright_cookies_to_netscape(cookies):
    """
    Playwright cookies → Netscape/Mozilla format
    (yt-dlp is format mein cookies padhta hai)
    """
    lines = ["# Netscape HTTP Cookie File", "# Auto-generated by auto_cookie_refresh.py", ""]
    for c in cookies:
        domain    = c.get("domain", "")
        flag      = "TRUE" if domain.startswith(".") else "FALSE"
        path      = c.get("path", "/")
        secure    = "TRUE" if c.get("secure", False) else "FALSE"
        expires   = str(int(c.get("expires", 0))) if c.get("expires") else "0"
        name      = c.get("name", "")
        value     = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines)

# ── Main refresh function ─────────────────────────────────────────────────────
def refresh_cookies(headless=True):
    """
    Playwright se YouTube login karke cookies save karo.
    Returns True on success, False on failure.
    """
    try:
        from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
    except ImportError:
        log.error("Playwright install nahi: pip install playwright && playwright install chromium --with-deps")
        return False

    email, password = load_credentials()

    log.info(f"Cookie refresh shuru — headless={headless}")

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=headless,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",         # EC2 pe /dev/shm chota hota hai
                "--disable-gpu",
                "--disable-blink-features=AutomationControlled",   # bot detection bypass
            ]
        )

        context = browser.new_context(
            viewport={"width": 1280, "height": 720},
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            locale="en-US",
        )

        page = context.new_page()

        try:
            # ── Step 1: YouTube open karo ──────────────────────────────────
            log.info("YouTube khol raha hoon...")
            page.goto("https://accounts.google.com/signin/v2/identifier?service=youtube", timeout=30000)
            time.sleep(2)

            # ── Step 2: Email enter karo ───────────────────────────────────
            log.info("Email enter kar raha hoon...")
            page.wait_for_selector('input[type="email"]', timeout=15000)
            page.fill('input[type="email"]', email)
            page.keyboard.press("Enter")
            time.sleep(2)

            # ── Step 3: Password enter karo ────────────────────────────────
            log.info("Password enter kar raha hoon...")
            page.wait_for_selector('input[type="password"]', timeout=15000)
            page.fill('input[type="password"]', password)
            page.keyboard.press("Enter")
            time.sleep(3)

            # ── Step 4: Login confirm ho ────────────────────────────────────
            # Check karo ke login ho gayi — YouTube pe redirect hona chahiye
            try:
                page.wait_for_url("*://www.youtube.com/**", timeout=20000)
                log.info("✅ YouTube pe redirect ho gaya — login successful")
            except PWTimeout:
                # Shayad 2FA ya verification page aa gayi
                current_url = page.url
                log.warning(f"YouTube redirect nahi hua. Current URL: {current_url}")

                # 2FA check
                if "challenge" in current_url or "signin/challenge" in current_url:
                    log.error("❌ 2FA/Verification required — is account mein 2FA band karo ya app password use karo")
                    browser.close()
                    return False

                # Manual wait — shayad extra page aa gayi
                log.info("10 sec wait kar raha hoon...")
                time.sleep(10)

                if "youtube.com" not in page.url:
                    log.error(f"❌ Login fail — URL: {page.url}")
                    browser.close()
                    return False

            # ── Step 5: YouTube.com pe jao (ensure correct domain) ─────────
            page.goto("https://www.youtube.com", timeout=20000)
            time.sleep(3)

            # ── Step 6: Cookies extract karo ──────────────────────────────
            log.info("Cookies extract kar raha hoon...")
            all_cookies = context.cookies(["https://www.youtube.com", "https://accounts.google.com"])

            # Sirf YouTube related cookies rakhna
            yt_domains  = {".youtube.com", "youtube.com", ".google.com", "google.com",
                           "accounts.google.com", ".accounts.google.com"}
            yt_cookies  = [c for c in all_cookies if c.get("domain","") in yt_domains]

            if len(yt_cookies) < 5:
                log.error(f"❌ Bahut kam cookies mili: {len(yt_cookies)} — login fail lag raha hai")
                browser.close()
                return False

            log.info(f"✅ {len(yt_cookies)} cookies mili")

            # ── Step 7: Netscape format mein save karo ─────────────────────
            cookie_content = playwright_cookies_to_netscape(yt_cookies)

            # Backup purani cookies (agar kuch galat ho)
            if os.path.exists(COOKIE_FILE):
                backup = COOKIE_FILE + ".bak"
                shutil.copy2(COOKIE_FILE, backup)
                log.info(f"Purani cookies backup: {backup}")

            with open(COOKIE_FILE, "w") as f:
                f.write(cookie_content)

            size = os.path.getsize(COOKIE_FILE)
            log.info(f"✅ Cookies saved: {COOKIE_FILE} ({size} bytes)")

            # ── Step 8: DB mein cookies enable mark karo ──────────────────
            _db_enable_cookies()

            # ── Step 9: Last refresh time save karo ───────────────────────
            _save_refresh_time()

            browser.close()
            log.info("✅ Cookie refresh complete!")
            return True

        except Exception as e:
            log.error(f"❌ Refresh error: {e}")
            try: browser.close()
            except: pass
            return False

# ── DB helpers ────────────────────────────────────────────────────────────────
def _db_enable_cookies():
    """Bot DB mein youtube_cookies_enabled = 1 set karo."""
    try:
        conn = sqlite3.connect(DB_PATH, timeout=10)
        conn.execute(
            "INSERT OR REPLACE INTO config(key,value) VALUES('youtube_cookies_enabled','1')"
        )
        conn.commit()
        conn.close()
        log.info("✅ DB mein youtube_cookies_enabled = 1 set ho gayi")
    except Exception as e:
        log.warning(f"DB update fail (manual karo): {e}")

def _save_refresh_time():
    """Last refresh timestamp save karo."""
    try:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        conn = sqlite3.connect(DB_PATH, timeout=10)
        conn.execute(
            "INSERT OR REPLACE INTO config(key,value) VALUES('yt_cookies_last_refresh',?)", (ts,)
        )
        conn.commit()
        conn.close()
    except: pass

def check_cookie_health():
    """
    Current cookies check karo — valid hain ya nahi.
    Returns: (is_valid: bool, age_days: int, message: str)
    """
    if not os.path.exists(COOKIE_FILE):
        return False, 0, "Cookie file nahi hai"

    size = os.path.getsize(COOKIE_FILE)
    if size < 100:
        return False, 0, f"Cookie file bahut choti hai ({size} bytes)"

    # Age check
    import time as _time
    age_days = (_time.time() - os.path.getmtime(COOKIE_FILE)) / 86400

    if age_days > 10:
        return False, int(age_days), f"Cookies {int(age_days)} din purani hain — refresh zaroor"

    return True, int(age_days), f"Cookies theek hain ({int(age_days)} din purani)"

# ── CLI ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="YouTube Cookie Auto-Refresh")
    parser.add_argument("--headless", action="store_true", help="Headless mode (EC2 ke liye)")
    parser.add_argument("--check",    action="store_true", help="Sirf health check karo")
    parser.add_argument("--force",    action="store_true", help="Force refresh even if cookies valid hain")
    args = parser.parse_args()

    if args.check:
        valid, age, msg = check_cookie_health()
        status = "✅ VALID" if valid else "❌ INVALID"
        print(f"{status} — {msg}")
        sys.exit(0 if valid else 1)

    # Health check — agar theek hain aur force nahi to skip
    if not args.force:
        valid, age, msg = check_cookie_health()
        if valid:
            log.info(f"Cookies theek hain ({msg}) — refresh ki zaroorat nahi. --force se override karo.")
            sys.exit(0)

    # Refresh karo
    success = refresh_cookies(headless=args.headless)
    sys.exit(0 if success else 1)
